# Generated by Django 5.1.5 on 2025-05-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_appointment_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.availability'),
        ),
    ]
