# Generated by Django 5.1.5 on 2025-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0006_alter_appointment_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
    ]
