# Generated by Django 5.2.1 on 2025-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_area_governorate_doctorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
