# Generated by Django 5.2.1 on 2025-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_doctorprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
