# Generated by Django 5.2.1 on 2025-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_doctorprofile_bio_users_bio_users_fcm_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
    ]
